name: Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: Checkout
      uses: actions/checkout@v3
    - id: setup-java
      name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin
        cache: maven
    - id: setup-maven
      name: Install Maven 3.9.5
      run: |
        mkdir -p $HOME/tmp
        curl -o $HOME/tmp/apache-maven-3.9.5-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
        cd $HOME/tmp
        tar xzvf apache-maven-3.9.5-bin.tar.gz
        echo "$HOME/tmp/apache-maven-3.9.5/" >> $GITHUB_PATH
    - id: build
      name: Build
      run: mvn install
    - id: artifact
      name: Upload Jar
      uses: actions/upload-artifact@v3
      with:
        name: PGM.jar
        path: target/PGM.jar
        if-no-files-found: error
